<?php

namespace Kronthto\AOArchive\Omi\Parser;

class Item extends AbstractParser
{
    protected function getDefinition(): array
    {
        // Position of paddings not 100% certain
        return [
            'id' => 'int',
            'kind' => 'byte',
            'name' => 'string43', // 40 + padding
            'AbilityMin' => 'float',
            'AbilityMax' => 'float',
            'ReqRace' => 'short',
            'ReqGearStat' => 'stat',
            'ReqUnitKind' => 'short',
            'ReqMinLevel' => 'byte',
            'ReqMaxLevel' => 'byte',
            'ReqItemKind' => 'byte',
            'PaddingReqItemKind' => 1,
            'Weight' => 'int', // short + padding
            'HitRate' => 'float',
            'Defense' => 'byte',
            'PaddingDefense' => 3,
            'FractionResistance' => 'float', // 92 till here
            'NaturalFaction' => 'byte',
            'SpeedPenalty' => 'byte',
            'Range' => 'short',
            'Position' => 'byte',
            'Scarcity' => 'byte',
            'Endurance' => 'float',
            'AbrasionRate' => 'short',
            'Charging' => 'short',
            'Luck' => 'byte',
            'PaddingLuck' => 3,
            'MinTradeQuantity' => 'short',
            'Price' => 'uint',
            'CashPrice' => 'uint', // 120 till here
            'DesParameter1' => 'short',
            'DesParameter2' => 'short',
            'DesParameter3' => 'short',
            'DesParameter4' => 'short',
            'DesParameter5' => 'short',
            'DesParameter6' => 'short',
            'DesParameter7' => 'short',
            'DesParameter8' => 'short',
            'ParameterValue1' => 'float',
            'ParameterValue2' => 'float',
            'ParameterValue3' => 'float',
            'ParameterValue4' => 'float',
            'ParameterValue5' => 'float',
            'ParameterValue6' => 'float',
            'ParameterValue7' => 'float',
            'ParameterValue8' => 'float', // 168 till here
            'ReAttacktime' => 'uint',
            'Time' => 'int',
            'RepeatTime' => 'short',
            'Material' => 'short',
            'ReqMaterial' => 'short',
            'PaddingReqMaterial' => 2,
            'RangeAngle' => 'float',
            'UpgradeNum' => 'byte',
            'PaddingUpgradeNum' => 3,
            'LinkItem' => 'int',
            'MultiTarget' => 'byte',
            'PaddingMultiTarget' => 1,
            'ExplosionRange' => 'short',
            'ReactionRange' => 'short',
            'ShotNum' => 'byte',
            'MultiNum' => 'byte',
            'AttackTime' => 'short',
            'ReqSP' => 'uint8',
            'PaddingReqSP' => 1,
            'SummonMonster' => 'int',
            'NextSkill' => 'int',
            'SkillLevel' => 'byte',
            'SkillHitRate' => 'short',
            'SkillType' => 'byte',
            'SkillTargetType' => 'byte',
            'Caliber' => 'byte',
            'OrbitType' => 'byte',
            'PaddingOrbitType' => 1,
            'ItemAttribute' => 'long',
            'BoosterAngle' => 'float',
            'CameraPattern' => 'int',
            'SourceIndex' => 'int',
            'pParamOverlapIdxListPointer' => 4,
            'description' => 'string200',
            'EnchantCheckDestParam' => 'byte',
            'EnchantCheckDestParamPadding' => 3,
            'InvokingDestParamID' => 'int',
            'InvokingDestParamIDByUse' => 'int',
            'pInvokingDestParamListPointer' => 4,
            'pInvokingDestParamByUseListPointer' => 4,
            'IsTenderDropItem' => 'byte',
        ];
    }
}
